### ISSUE TITLE
Create forgot your password route

### ISSUE THREAD

**Issue by nortonbatista** [nortonbatista/bfrpg-toolkit#10]
## Description
There should be a link at the login view where the user could try to recover their password.

## Roadmap
- [ ] Link at login called "Forgot your password?".
- [ ] Require the user email.
- [ ] Always responds with: "Instructions to recover your password were sent to your email". Even if the user was not found.
- [ ] If the user was found, send an email with the instruction to recover the password

## Useful links
[Rails 7.1 Authentication From Scratch](https://www.youtube.com/watch?v=Hb9WtQf9K60). The authentication in this app was build with this video, but the "forgot your password" step wasn't implemented yet.
